[env:esp32-c6-lcd147]
extends = esp32c6_base
board = esp32-c6-devkitc-1
board_level = pr
build_unflags =
  -D HAS_BLUETOOTH
  -D MESHTASTIC_EXCLUDE_BLUETOOTH
build_flags =
  ${esp32c6_base.build_flags}
  -D PRIVATE_HW
  -D ESP32C6_LCD147
  -D HAS_WIRE=0
  -I variants/esp32c6/ws_lcd147
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -ULED_BUILTIN
  -D HAS_BLUETOOTH=1
  -DCONFIG_BT_NIMBLE_EXT_ADV=1
  -DCONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=2
  -D NIMBLE_TWO

lib_deps = ${esp32c6_base.lib_deps}
  # renovate: datasource=custom.pio depName=LovyanGFX packageName=lovyan03/library/LovyanGFX
  lovyan03/LovyanGFX@1.2.19
  # renovate: datasource=custom.pio depName=NimBLE-Arduino packageName=h2zero/library/NimBLE-Arduino
  h2zero/NimBLE-Arduino@2.3.7

lib_ignore =
  NonBlockingRTTTL
  libpax
